# Generated by Django 5.1.7 on 2025-05-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SinavTurleri",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad", models.CharField(max_length=50, verbose_name="Sınav Adı")),
                (
                    "kod",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Sınav Kodu"
                    ),
                ),
                (
                    "aciklama",
                    models.TextField(blank=True, null=True, verbose_name="Açıklama"),
                ),
                ("aktif", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "ikon",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="İkon Kodu"
                    ),
                ),
                ("url", models.CharField(max_length=100, verbose_name="URL")),
            ],
            options={
                "verbose_name": "Sınav Türü",
                "verbose_name_plural": "Sınav Türleri",
            },
        ),
    ]
