# Generated by Django 5.1.7 on 2025-05-16 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SinavAltTur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad", models.CharField(max_length=100, verbose_name="Alt Tür Adı")),
                ("kod", models.CharField(max_length=20, verbose_name="Alt Tür Kodu")),
                (
                    "aciklama",
                    models.TextField(blank=True, null=True, verbose_name="Açıklama"),
                ),
                (
                    "ikon",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="İkon Kodu"
                    ),
                ),
                ("aktif", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "sinav_turu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alt_turler",
                        to="core.sinavturleri",
                        verbose_name="Bağlı Olduğu Sınav",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sınav Alt Türü",
                "verbose_name_plural": "Sınav Alt Türleri",
                "unique_together": {("sinav_turu", "kod")},
            },
        ),
        migrations.CreateModel(
            name="Ders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad", models.CharField(max_length=100, verbose_name="Ders Adı")),
                ("kod", models.CharField(max_length=20, verbose_name="Ders Kodu")),
                (
                    "aciklama",
                    models.TextField(blank=True, null=True, verbose_name="Açıklama"),
                ),
                (
                    "ikon",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="İkon Kodu"
                    ),
                ),
                ("aktif", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "alt_tur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dersler",
                        to="core.sinavalttur",
                        verbose_name="Bağlı Olduğu Alt Tür",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ders",
                "verbose_name_plural": "Dersler",
                "unique_together": {("alt_tur", "kod")},
            },
        ),
    ]
