# Generated by Django 5.1.7 on 2025-05-16 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_sinavalttur_ders"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ders",
            unique_together={("alt_tur", "kod")},
        ),
        migrations.AddField(
            model_name="ders",
            name="sinav_turu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dersler",
                to="core.sinavturleri",
                verbose_name="Bağlı Olduğu Sınav Türü",
            ),
        ),
        migrations.AlterField(
            model_name="ders",
            name="alt_tur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dersler",
                to="core.sinavalttur",
                verbose_name="Bağlı Olduğu Alt Tür",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ders",
            unique_together={("alt_tur", "kod"), ("sinav_turu", "kod")},
        ),
    ]
