# Generated by Django 5.1.7 on 2025-05-16 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_ders_unique_together_ders_sinav_turu_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ders",
            unique_together={("alt_tur", "kod")},
        ),
    ]
