# Generated by Django 5.1.7 on 2025-05-18 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_ders_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="Unite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad", models.CharField(max_length=200, verbose_name="Ünite Adı")),
                (
                    "sira_no",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Sıra Numarası"
                    ),
                ),
                (
                    "aciklama",
                    models.TextField(blank=True, null=True, verbose_name="Açıklama"),
                ),
                ("aktif", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "ders",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uniteler",
                        to="core.ders",
                        verbose_name="Bağlı Olduğu Ders",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ünite",
                "verbose_name_plural": "Üniteler",
                "ordering": ["ders", "sira_no"],
                "unique_together": {("ders", "ad"), ("ders", "sira_no")},
            },
        ),
        migrations.CreateModel(
            name="Konu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad", models.CharField(max_length=200, verbose_name="Konu Adı")),
                (
                    "sira_no",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Sıra Numarası"
                    ),
                ),
                (
                    "aciklama",
                    models.TextField(blank=True, null=True, verbose_name="Açıklama"),
                ),
                ("aktif", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "unite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="konular",
                        to="core.unite",
                        verbose_name="Bağlı Olduğu Ünite",
                    ),
                ),
            ],
            options={
                "verbose_name": "Konu",
                "verbose_name_plural": "Konular",
                "ordering": ["unite", "sira_no"],
                "unique_together": {("unite", "ad"), ("unite", "sira_no")},
            },
        ),
    ]
