# Generated by Django 5.1.7 on 2025-05-20 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_unite_konu"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KonuTakip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tamamlandi",
                    models.BooleanField(default=False, verbose_name="Tamamlandı"),
                ),
                (
                    "tamamlanma_tarihi",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tamamlanma Tarihi"
                    ),
                ),
                (
                    "olusturulma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                (
                    "notlar",
                    models.TextField(blank=True, null=True, verbose_name="Notlar"),
                ),
                (
                    "konu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="takip_edenler",
                        to="core.konu",
                        verbose_name="Konu",
                    ),
                ),
                (
                    "kullanici",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="konu_takipleri",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Konu Takip",
                "verbose_name_plural": "Konu Takipleri",
                "unique_together": {("kullanici", "konu")},
            },
        ),
    ]
