# Generated by Django 5.1.7 on 2025-05-20 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_konutakip"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HedefDurumu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad", models.CharField(max_length=100)),
                (
                    "renk",
                    models.CharField(
                        help_text="Örn: success, danger, warning", max_length=50
                    ),
                ),
                ("sira_no", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Hedef Durumu",
                "verbose_name_plural": "Hedef Durumları",
                "ordering": ["sira_no"],
            },
        ),
        migrations.CreateModel(
            name="HedefTuru",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad", models.CharField(max_length=100)),
                ("sira_no", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Hedef Türü",
                "verbose_name_plural": "Hedef Türleri",
                "ordering": ["sira_no"],
            },
        ),
        migrations.CreateModel(
            name="Hedef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "baslik",
                    models.CharField(max_length=255, verbose_name="Hedef Başlığı"),
                ),
                (
                    "aciklama",
                    models.TextField(blank=True, null=True, verbose_name="Açıklama"),
                ),
                ("baslangic_tarihi", models.DateField(verbose_name="Başlangıç Tarihi")),
                ("bitis_tarihi", models.DateField(verbose_name="Bitiş Tarihi")),
                (
                    "tamamlanma_orani",
                    models.IntegerField(default=0, verbose_name="Tamamlanma Oranı (%)"),
                ),
                (
                    "olusturulma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                (
                    "kullanici",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
                (
                    "durum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.hedefdurumu",
                        verbose_name="Durum",
                    ),
                ),
                (
                    "hedef_turu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.hedefturu",
                        verbose_name="Hedef Türü",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hedef",
                "verbose_name_plural": "Hedefler",
                "ordering": ["-olusturulma_tarihi"],
            },
        ),
        migrations.CreateModel(
            name="HedefIlerleme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("yorum", models.TextField(verbose_name="İlerleme Notu")),
                (
                    "tamamlanma_orani",
                    models.IntegerField(verbose_name="Tamamlanma Oranı (%)"),
                ),
                ("olusturulma_tarihi", models.DateTimeField(auto_now_add=True)),
                (
                    "hedef",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ilerlemeler",
                        to="core.hedef",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hedef İlerleme",
                "verbose_name_plural": "Hedef İlerlemeleri",
                "ordering": ["-olusturulma_tarihi"],
            },
        ),
    ]
