# Generated by Django 5.1.7 on 2025-05-20 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_hedefdurumu_hedefturu_hedef_hedefilerleme"),
    ]

    operations = [
        migrations.DeleteModel(
            name="KonuTakip",
        ),
    ]
