# Generated by Django 5.1.7 on 2025-05-20 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_delete_konutakip"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hedef",
            name="durum",
        ),
        migrations.RemoveField(
            model_name="hedef",
            name="hedef_turu",
        ),
        migrations.RemoveField(
            model_name="hedef",
            name="kullanici",
        ),
        migrations.RemoveField(
            model_name="hedefilerleme",
            name="hedef",
        ),
        migrations.DeleteModel(
            name="HedefDurumu",
        ),
        migrations.DeleteModel(
            name="HedefTuru",
        ),
        migrations.DeleteModel(
            name="Hedef",
        ),
        migrations.DeleteModel(
            name="HedefIlerleme",
        ),
    ]
