# Generated by Django 5.1.7 on 2025-05-20 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_remove_hedef_durum_remove_hedef_hedef_turu_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CalismaHedefi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "baslik",
                    models.CharField(max_length=200, verbose_name="Hedef Başlığı"),
                ),
                (
                    "aciklama",
                    models.TextField(blank=True, null=True, verbose_name="Açıklama"),
                ),
                ("baslangic_tarihi", models.DateField(verbose_name="Başlangıç Tarihi")),
                ("bitis_tarihi", models.DateField(verbose_name="Bitiş Tarihi")),
                (
                    "periyot",
                    models.CharField(
                        choices=[("G", "Günlük"), ("H", "Haftalık"), ("A", "Aylık")],
                        default="G",
                        max_length=1,
                        verbose_name="Periyot",
                    ),
                ),
                (
                    "durum",
                    models.CharField(
                        choices=[
                            ("A", "Aktif"),
                            ("T", "Tamamlandı"),
                            ("I", "İptal Edildi"),
                        ],
                        default="A",
                        max_length=1,
                        verbose_name="Durum",
                    ),
                ),
                ("olusturulma_tarihi", models.DateTimeField(auto_now_add=True)),
                ("guncelleme_tarihi", models.DateTimeField(auto_now=True)),
                (
                    "kullanici",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calisma_hedefleri",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Çalışma Hedefi",
                "verbose_name_plural": "Çalışma Hedefleri",
                "ordering": ["-olusturulma_tarihi"],
            },
        ),
        migrations.CreateModel(
            name="CalismaPlani",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "baslik",
                    models.CharField(max_length=200, verbose_name="Plan Başlığı"),
                ),
                (
                    "aciklama",
                    models.TextField(blank=True, null=True, verbose_name="Açıklama"),
                ),
                (
                    "plan_turu",
                    models.CharField(
                        choices=[
                            ("D", "Ders Çalışma"),
                            ("K", "Konu Tekrarı"),
                            ("M", "Deneme Sınavı"),
                        ],
                        max_length=1,
                        verbose_name="Plan Türü",
                    ),
                ),
                ("planlanan_tarih", models.DateField(verbose_name="Planlanan Tarih")),
                (
                    "planlanan_sure",
                    models.PositiveIntegerField(verbose_name="Planlanan Süre (dakika)"),
                ),
                (
                    "gerceklesen_sure",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Gerçekleşen Süre (dakika)"
                    ),
                ),
                (
                    "durum",
                    models.CharField(
                        choices=[
                            ("B", "Bekliyor"),
                            ("T", "Tamamlandı"),
                            ("I", "İptal Edildi"),
                        ],
                        default="B",
                        max_length=1,
                        verbose_name="Durum",
                    ),
                ),
                ("olusturulma_tarihi", models.DateTimeField(auto_now_add=True)),
                ("guncelleme_tarihi", models.DateTimeField(auto_now=True)),
                (
                    "ders",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calisma_planlari",
                        to="core.ders",
                        verbose_name="Ders",
                    ),
                ),
                (
                    "hedef",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calisma_planlari",
                        to="core.calismahedefi",
                        verbose_name="Bağlı Olduğu Hedef",
                    ),
                ),
                (
                    "konu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calisma_planlari",
                        to="core.konu",
                        verbose_name="Konu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Çalışma Planı",
                "verbose_name_plural": "Çalışma Planları",
                "ordering": ["planlanan_tarih", "olusturulma_tarihi"],
            },
        ),
        migrations.CreateModel(
            name="Hatirlatici",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "baslik",
                    models.CharField(
                        max_length=200, verbose_name="Hatırlatıcı Başlığı"
                    ),
                ),
                (
                    "aciklama",
                    models.TextField(blank=True, null=True, verbose_name="Açıklama"),
                ),
                ("tarih", models.DateField(verbose_name="Tarih")),
                ("saat", models.TimeField(blank=True, null=True, verbose_name="Saat")),
                (
                    "oncelik",
                    models.CharField(
                        choices=[("D", "Düşük"), ("N", "Normal"), ("Y", "Yüksek")],
                        default="N",
                        max_length=1,
                        verbose_name="Öncelik",
                    ),
                ),
                (
                    "durum",
                    models.CharField(
                        choices=[
                            ("A", "Aktif"),
                            ("T", "Tamamlandı"),
                            ("I", "İptal Edildi"),
                        ],
                        default="A",
                        max_length=1,
                        verbose_name="Durum",
                    ),
                ),
                ("olusturulma_tarihi", models.DateTimeField(auto_now_add=True)),
                ("guncelleme_tarihi", models.DateTimeField(auto_now=True)),
                (
                    "kullanici",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hatirlaticilar",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hatırlatıcı",
                "verbose_name_plural": "Hatırlatıcılar",
                "ordering": ["tarih", "saat"],
            },
        ),
        migrations.CreateModel(
            name="YapilacakListesi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "baslik",
                    models.CharField(max_length=200, verbose_name="Görev Başlığı"),
                ),
                (
                    "aciklama",
                    models.TextField(blank=True, null=True, verbose_name="Açıklama"),
                ),
                (
                    "son_tarih",
                    models.DateField(blank=True, null=True, verbose_name="Son Tarih"),
                ),
                (
                    "oncelik",
                    models.CharField(
                        choices=[("D", "Düşük"), ("N", "Normal"), ("Y", "Yüksek")],
                        default="N",
                        max_length=1,
                        verbose_name="Öncelik",
                    ),
                ),
                (
                    "durum",
                    models.CharField(
                        choices=[
                            ("A", "Aktif"),
                            ("T", "Tamamlandı"),
                            ("I", "İptal Edildi"),
                        ],
                        default="A",
                        max_length=1,
                        verbose_name="Durum",
                    ),
                ),
                ("olusturulma_tarihi", models.DateTimeField(auto_now_add=True)),
                ("guncelleme_tarihi", models.DateTimeField(auto_now=True)),
                (
                    "kullanici",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="yapilacaklar",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yapılacak",
                "verbose_name_plural": "Yapılacaklar",
                "ordering": ["durum", "oncelik", "son_tarih", "olusturulma_tarihi"],
            },
        ),
    ]
