# Generated by Django 5.1.7 on 2025-05-20 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_calismahedefi_calismaplani_hatirlatici_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calismaplani",
            name="hedef",
        ),
        migrations.RemoveField(
            model_name="calismaplani",
            name="ders",
        ),
        migrations.RemoveField(
            model_name="calismaplani",
            name="konu",
        ),
        migrations.RemoveField(
            model_name="hatirlatici",
            name="kullanici",
        ),
        migrations.RemoveField(
            model_name="yapilacaklistesi",
            name="kullanici",
        ),
        migrations.DeleteModel(
            name="CalismaHedefi",
        ),
        migrations.DeleteModel(
            name="CalismaPlani",
        ),
        migrations.DeleteModel(
            name="Hatirlatici",
        ),
        migrations.DeleteModel(
            name="YapilacakListesi",
        ),
    ]
