# Generated by Django 5.1.7 on 2025-06-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_userprofile_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Telefon Numarası"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_pictures/",
                verbose_name="Profil Fotoğrafı",
            ),
        ),
    ]
