# Generated by Django 5.1.7 on 2025-06-04 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_userprofile_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="Doğum Tarihi"),
        ),
    ]
