# Generated by Django 5.1.7 on 2025-06-04 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_userprofile_email_verified_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="E-posta Adresi"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=6, unique=True, verbose_name="Doğrulama Kodu"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Zamanı"
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(default=False, verbose_name="Kullanıldı mı?"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "E-posta Doğrulama Kodu",
                "verbose_name_plural": "E-posta Doğrulama Kodları",
            },
        ),
    ]
