# Generated by Django 5.1.7 on 2025-06-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_emailverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="ders",
            name="soru_sayisi",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Toplam Soru Sayısı"
            ),
        ),
    ]
