# Generated by Django 5.1.7 on 2025-05-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="yksoturum",
            name="sinav_tarihi",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Sınav Tarihi"
            ),
        ),
    ]
