# Generated by Django 5.1.7 on 2025-05-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yks", "0002_yksoturum_sinav_tarihi"),
    ]

    operations = [
        migrations.AddField(
            model_name="yksoturum",
            name="yil",
            field=models.IntegerField(default=2023, verbose_name="Sınav Yılı"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="yksoturum",
            name="kod",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name="yksoturum",
            unique_together={("kod", "yil")},
        ),
    ]
