# Generated by Django 5.1.7 on 2025-05-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yks", "0003_yksoturum_yil_alter_yksoturum_kod_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="yksoturum",
            name="yil",
            field=models.IntegerField(default=2025, verbose_name="Sınav Yılı"),
        ),
    ]
