# Generated by Django 5.1.7 on 2025-05-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yks", "0004_alter_yksoturum_yil"),
    ]

    operations = [
        migrations.AddField(
            model_name="yksoturum",
            name="durum",
            field=models.CharField(
                choices=[("Bekliyor", "Bekliyor"), ("Geçmiş", "Geçmiş")],
                default="Bekliyor",
                max_length=15,
                verbose_name="Durum",
            ),
        ),
    ]
