# Generated by Django 5.1.7 on 2025-05-20 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_calismahedefi_calismaplani_hatirlatici_and_more"),
        ("yks", "0006_calismahedefi_calismaplani_hatirlatici_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calismaplani",
            name="hedef",
        ),
        migrations.RemoveField(
            model_name="calismaplani",
            name="ders",
        ),
        migrations.RemoveField(
            model_name="calismaplani",
            name="konu",
        ),
        migrations.RemoveField(
            model_name="hatirlatici",
            name="kullanici",
        ),
        migrations.RemoveField(
            model_name="yapilacaklistesi",
            name="kullanici",
        ),
        migrations.CreateModel(
            name="KonuTakip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tamamlandi",
                    models.BooleanField(default=True, verbose_name="Tamamlandı"),
                ),
                (
                    "tamamlanma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Tamamlanma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                (
                    "notlar",
                    models.TextField(blank=True, null=True, verbose_name="Notlar"),
                ),
                (
                    "konu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tamamlayanlar",
                        to="core.konu",
                        verbose_name="Konu",
                    ),
                ),
                (
                    "kullanici",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tamamlanan_konular",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Konu Takip",
                "verbose_name_plural": "Konu Takipleri",
                "ordering": ["-tamamlanma_tarihi"],
                "unique_together": {("kullanici", "konu")},
            },
        ),
        migrations.DeleteModel(
            name="CalismaHedefi",
        ),
        migrations.DeleteModel(
            name="CalismaPlani",
        ),
        migrations.DeleteModel(
            name="Hatirlatici",
        ),
        migrations.DeleteModel(
            name="YapilacakListesi",
        ),
    ]
