# Generated by Django 5.1.7 on 2025-05-20 13:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_remove_calismaplani_hedef_remove_calismaplani_ders_and_more"),
        ("yks", "0007_remove_calismaplani_hedef_remove_calismaplani_ders_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HedefTuru",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ad",
                    models.CharField(
                        choices=[
                            ("Günlük", "Günlük"),
                            ("Haftalık", "Haftalık"),
                            ("Aylık", "Aylık"),
                            ("Özel", "Özel"),
                        ],
                        default="Günlük",
                        max_length=20,
                        verbose_name="Hedef Türü",
                    ),
                ),
                (
                    "aciklama",
                    models.TextField(blank=True, null=True, verbose_name="Açıklama"),
                ),
            ],
            options={
                "verbose_name": "Hedef Türü",
                "verbose_name_plural": "Hedef Türleri",
            },
        ),
        migrations.CreateModel(
            name="CalismaPlanı",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tarih",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Çalışma Tarihi"
                    ),
                ),
                (
                    "toplam_calisma_suresi",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Toplam Çalışma Süresi (dakika)"
                    ),
                ),
                (
                    "notlar",
                    models.TextField(blank=True, null=True, verbose_name="Notlar"),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                (
                    "kullanici",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calisma_planlari",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Çalışma Planı",
                "verbose_name_plural": "Çalışma Planları",
                "ordering": ["-tarih"],
                "unique_together": {("kullanici", "tarih")},
            },
        ),
        migrations.CreateModel(
            name="CalismaOturumu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("baslangic_saati", models.TimeField(verbose_name="Başlangıç Saati")),
                ("bitis_saati", models.TimeField(verbose_name="Bitiş Saati")),
                ("sure", models.PositiveIntegerField(verbose_name="Süre (dakika)")),
                (
                    "tamamlandi",
                    models.BooleanField(default=False, verbose_name="Tamamlandı"),
                ),
                (
                    "notlar",
                    models.TextField(blank=True, null=True, verbose_name="Notlar"),
                ),
                (
                    "ders",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calisma_oturumlari",
                        to="core.ders",
                        verbose_name="Ders",
                    ),
                ),
                (
                    "konu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calisma_oturumlari",
                        to="core.konu",
                        verbose_name="Konu",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oturumlar",
                        to="yks.calismaplanı",
                        verbose_name="Çalışma Planı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Çalışma Oturumu",
                "verbose_name_plural": "Çalışma Oturumları",
                "ordering": ["baslangic_saati"],
            },
        ),
        migrations.CreateModel(
            name="Gorev",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "baslik",
                    models.CharField(max_length=200, verbose_name="Görev Başlığı"),
                ),
                (
                    "aciklama",
                    models.TextField(blank=True, null=True, verbose_name="Açıklama"),
                ),
                (
                    "son_tarih",
                    models.DateField(blank=True, null=True, verbose_name="Son Tarih"),
                ),
                (
                    "durum",
                    models.CharField(
                        choices=[
                            ("Bekliyor", "Bekliyor"),
                            ("Tamamlandı", "Tamamlandı"),
                            ("Ertelendi", "Ertelendi"),
                            ("İptal", "İptal"),
                        ],
                        default="Bekliyor",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "oncelik",
                    models.CharField(
                        choices=[
                            ("Düşük", "Düşük"),
                            ("Orta", "Orta"),
                            ("Yüksek", "Yüksek"),
                        ],
                        default="Orta",
                        max_length=10,
                        verbose_name="Öncelik",
                    ),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                (
                    "kullanici",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gorevler",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Görev",
                "verbose_name_plural": "Görevler",
                "ordering": ["son_tarih", "oncelik"],
            },
        ),
        migrations.CreateModel(
            name="Hatirlatici",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "baslik",
                    models.CharField(
                        max_length=200, verbose_name="Hatırlatıcı Başlığı"
                    ),
                ),
                (
                    "aciklama",
                    models.TextField(blank=True, null=True, verbose_name="Açıklama"),
                ),
                (
                    "hatirlatma_tarihi",
                    models.DateTimeField(verbose_name="Hatırlatma Tarihi ve Saati"),
                ),
                ("tekrar", models.BooleanField(default=False, verbose_name="Tekrarla")),
                (
                    "tekrar_periyodu",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Tekrar Periyodu",
                    ),
                ),
                ("aktif", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                (
                    "kullanici",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hatirlaticilar",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hatırlatıcı",
                "verbose_name_plural": "Hatırlatıcılar",
                "ordering": ["hatirlatma_tarihi"],
            },
        ),
        migrations.CreateModel(
            name="Hedef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "baslik",
                    models.CharField(max_length=200, verbose_name="Hedef Başlığı"),
                ),
                (
                    "aciklama",
                    models.TextField(blank=True, null=True, verbose_name="Açıklama"),
                ),
                (
                    "baslangic_tarihi",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Başlangıç Tarihi",
                    ),
                ),
                (
                    "bitis_tarihi",
                    models.DateField(
                        blank=True, null=True, verbose_name="Bitiş Tarihi"
                    ),
                ),
                (
                    "durum",
                    models.CharField(
                        choices=[
                            ("Aktif", "Aktif"),
                            ("Tamamlandı", "Tamamlandı"),
                            ("İptal", "İptal"),
                        ],
                        default="Aktif",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "oncelik",
                    models.CharField(
                        choices=[
                            ("Düşük", "Düşük"),
                            ("Orta", "Orta"),
                            ("Yüksek", "Yüksek"),
                        ],
                        default="Orta",
                        max_length=10,
                        verbose_name="Öncelik",
                    ),
                ),
                (
                    "tamamlanma_orani",
                    models.IntegerField(default=0, verbose_name="Tamamlanma Oranı (%)"),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                (
                    "ders",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hedefler",
                        to="core.ders",
                        verbose_name="İlgili Ders",
                    ),
                ),
                (
                    "kullanici",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hedefler",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
                (
                    "tur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hedefler",
                        to="yks.hedefturu",
                        verbose_name="Hedef Türü",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hedef",
                "verbose_name_plural": "Hedefler",
                "ordering": ["-olusturma_tarihi"],
            },
        ),
    ]
