# Generated by Django 5.1.7 on 2025-06-02 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_remove_calismaplani_hedef_remove_calismaplani_ders_and_more"),
        ("yks", "0008_hedefturu_calismaplanı_calismaoturumu_gorev_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="KonuTakipHedefi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("baslangic_tarihi", models.DateField(verbose_name="Başlangıç Tarihi")),
                ("bitis_tarihi", models.DateField(verbose_name="Bitiş Tarihi")),
                (
                    "ders",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.ders",
                        verbose_name="Ders",
                    ),
                ),
                (
                    "hedef",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="konu_takip_detay",
                        to="yks.hedef",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KonuTakipHedefKonu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tamamlandi",
                    models.BooleanField(default=False, verbose_name="Tamamlandı mı?"),
                ),
                (
                    "konu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.konu",
                        verbose_name="Konu",
                    ),
                ),
                (
                    "konu_takip_hedefi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="konular",
                        to="yks.konutakiphedefi",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SoruCozumHedefi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "toplam_soru",
                    models.PositiveIntegerField(verbose_name="Toplam Soru Hedefi"),
                ),
                (
                    "cozulmus_soru",
                    models.PositiveIntegerField(default=0, verbose_name="Çözülen Soru"),
                ),
                ("baslangic_tarihi", models.DateField(verbose_name="Başlangıç Tarihi")),
                ("bitis_tarihi", models.DateField(verbose_name="Bitiş Tarihi")),
                (
                    "ders",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.ders",
                        verbose_name="Ders",
                    ),
                ),
                (
                    "hedef",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soru_cozum_detay",
                        to="yks.hedef",
                    ),
                ),
            ],
        ),
    ]
