# Generated by Django 5.1.7 on 2025-06-02 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("yks", "0009_konutakiphedefi_konutakiphedefkonu_sorucozumhedefi"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="konutakiphedefkonu",
            name="konu_takip_hedefi",
        ),
        migrations.RemoveField(
            model_name="konutakiphedefkonu",
            name="konu",
        ),
        migrations.RemoveField(
            model_name="sorucozumhedefi",
            name="ders",
        ),
        migrations.RemoveField(
            model_name="sorucozumhedefi",
            name="hedef",
        ),
        migrations.DeleteModel(
            name="KonuTakipHedefi",
        ),
        migrations.DeleteModel(
            name="KonuTakipHedefKonu",
        ),
        migrations.DeleteModel(
            name="SoruCozumHedefi",
        ),
    ]
