# Generated by Django 5.1.7 on 2025-06-03 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yks", "0011_konutakiphedefi_sorucozumhedefi_konutakiphedefkonu"),
    ]

    operations = [
        migrations.CreateModel(
            name="HedefDurum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ad",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Durum Adı"
                    ),
                ),
            ],
            options={
                "verbose_name": "Hedef Durumu",
                "verbose_name_plural": "Hedef Durumları",
            },
        ),
        migrations.RemoveField(
            model_name="hedef",
            name="durum",
        ),
        migrations.AddField(
            model_name="hedef",
            name="hedef_durum",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hedefler",
                to="yks.hedefdurum",
                verbose_name="Hedef Durumu",
            ),
        ),
    ]
