# Generated by Django 5.1.7 on 2025-06-03 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("yks", "0012_hedefdurum_remove_hedef_durum_hedef_hedef_durum"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Gorev",
        ),
    ]
