# Generated by Django 5.1.7 on 2025-06-04 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("yks", "0013_delete_gorev"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hatirlatici",
            name="tekrar",
        ),
        migrations.RemoveField(
            model_name="hatirlatici",
            name="tekrar_periyodu",
        ),
    ]
