# Generated by Django 5.1.7 on 2025-06-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yks", "0014_remove_hatirlatici_tekrar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hatirlatici",
            name="sent",
            field=models.BooleanField(
                default=False, verbose_name="E-posta gönderildi mi?"
            ),
        ),
    ]
