# Generated by Django 5.1.7 on 2025-06-04 13:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_emailverification"),
        ("yks", "0015_hatirlatici_sent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DenemeSinavSonucu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sinav_tarihi",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Sınav Tarihi"
                    ),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                (
                    "kullanici",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deneme_sinav_sonuclari",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
                (
                    "oturum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deneme_sinav_sonuclari",
                        to="yks.yksoturum",
                        verbose_name="Sınav Oturumu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Deneme Sınav Sonucu",
                "verbose_name_plural": "Deneme Sınav Sonuçları",
                "ordering": ["-sinav_tarihi", "-olusturma_tarihi"],
            },
        ),
        migrations.CreateModel(
            name="DenemeSinavDersSonucu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dogru",
                    models.PositiveIntegerField(default=0, verbose_name="Doğru Sayısı"),
                ),
                (
                    "yanlis",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Yanlış Sayısı"
                    ),
                ),
                (
                    "bos",
                    models.PositiveIntegerField(default=0, verbose_name="Boş Sayısı"),
                ),
                ("net", models.FloatField(default=0.0, verbose_name="Net Sayısı")),
                (
                    "ders",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deneme_sinav_sonuclari",
                        to="core.ders",
                        verbose_name="Ders",
                    ),
                ),
                (
                    "deneme_sinav_sonucu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ders_sonuclari",
                        to="yks.denemesinavsonucu",
                        verbose_name="Deneme Sınav Sonucu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Deneme Sınav Ders Sonucu",
                "verbose_name_plural": "Deneme Sınav Ders Sonuçları",
                "unique_together": {("deneme_sinav_sonucu", "ders")},
            },
        ),
    ]
