# Generated by Django 5.1.7 on 2025-06-04 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_ders_soru_sayisi"),
        ("yks", "0016_denemesinavsonucu_denemesinavderssonucu"),
    ]

    operations = [
        migrations.AddField(
            model_name="yksoturum",
            name="sinav_alt_tur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="yks_oturumlar",
                to="core.sinavalttur",
                verbose_name="Sınav Alt Türü",
            ),
        ),
    ]
