# Generated by Django 5.1.7 on 2025-06-04 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_ders_soru_sayisi"),
        ("yks", "0017_yksoturum_sinav_alt_tur"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="denemesinavsonucu",
            name="oturum",
        ),
        migrations.AddField(
            model_name="denemesinavsonucu",
            name="sinav_alt_tur",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deneme_sinav_sonuclari",
                to="core.sinavalttur",
                verbose_name="Sınav Alt Türü",
            ),
            preserve_default=False,
        ),
    ]
